In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
X = iris.data
y = iris.target


In [4]:
#Mean
np.mean(X, axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [5]:
#Standard Deviation
np.std(X, axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [6]:
#Variance
np.var(X, axis=0)

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [7]:
#Percentile
np.percentile(X[:, 0], 25)

np.float64(5.1)

In [8]:
#Quantile
np.quantile(X[:, 0], 0.75)

np.float64(6.4)